let dogArr =[
    {
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },
    {
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },{
        name:'Мультик',
        photo:'./src/assets/cartoon/1.jpg',
        allPhoto:['./src/assets/cartoon/2.jpg','./src/assets/cartoon/3.jpg'],
        gender:'Самец',
        type:'Dogs',
        old:'14 лет',
        about_old:'6 и более',
        size:'средний',
        information:'Мультик ласковый, общительный , преданный',
        tx:'Мультик -инвалид только с одной рабочей лапой, задних нет',
    },
    {
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },
    {
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },{
        name:'Анабель',
        photo:'./src/assets/Anabel/1.jpg',
        allPhoto:['./src/assets/Anabel/2.jpg','./src/assets/Anabel/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'5 лет',
        about_old:'1-5 лет',
        size:'средний',
        information:'Анабель-девочка с характером',
        tx:'Попала под поезд еще маленьким щенком, в результате чего лишилась обеих передних лап',
    },
    {
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },{
        name:'Иви',
        photo:'./src/assets/ivi/1.jpg',
        allPhoto:['./src/assets/ivi/2.jpg','./src/assets/ivi/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'1,5 года',
        about_old:'1-5 лет',
        size:'средний',
        information:'Иви очень пугливая собачка, очень осторожная и спокойная',
        tx:null,
    },
    {
        name:'Лора',
        photo:'./src/assets/lora/1.jpg',
        allPhoto:['./src/assets/lora/2.jpg','./src/assets/lora/3.jpg'],
        gender:'Самка',
        type:'Dogs',
        old:'7 лет',
        about_old:'6 и более',
        size:'большой',
        information:'Лора-метис овчарки, очень преданная и активная ',
        tx:'К сожалению, у Лоры проблемы  с задними лапами',
    },

]
